{{- if .Values.persistence.cache.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.cache.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size | quote }}
  {{- include "common.storage.class" ( dict "persistence" .Values.persistence "global" .Values.global) | nindent 2 }}
{{- end }}
