# settings.toml

[default]
DEBUG = 0

[default.app]

[default.minio]
URL = "localhost:8080"
BUCKET = "images"
ACCESS_KEY = "WcZkHqodv1fffytkLe2a"
SECRET_KEY = "1YloZi2W4NnMDPNHVtZhzhx8JYEmeuxQ7AOMRN9a"

[default.cache]
SIZE = 10
DIR = "/tmp/cache"

[default.logging]
LOG_FILENAME = "/tmp/imageserver.log"
LEVEL = "INFO"
FORMAT = "[%(asctime)s | %(levelname)s] - %(filename)s:%(funcName)s:%(lineno)s - %(message)s"
MAX_BYTES = 10485760
BACKUP_COUNT = 5

[testing.app]
SLIDE_DIR = "/tmp/cache-imageserver"

# /usr/bin/mc admin user add s3 WcZkHqodv1fffytkLe2a 1YloZi2W4NnMDPNHVtZhzhx8JYEmeuxQ7AOMRN9a;