# settings.toml

[default]
DEBUG = 0

[default.app]

[default.imageserver]
url = "http://localhost:8000"

[default.cache]
SIZE = 10
DIR = "/tmp/cache-imageserver"

[default.logging]
LOG_FILENAME = "/tmp/imageserver.log"
LEVEL = "INFO"
FORMAT = "[%(asctime)s | %(levelname)s] - %(filename)s:%(funcName)s:%(lineno)s - %(message)s"
MAX_BYTES = 10485760
BACKUP_COUNT = 5

[testing.app]
SLIDE_DIR = "/tmp/cache-imageserver"
